### ISSUE TITLE
Logout is broken

### ISSUE THREAD

**Issue by evan10s** [HackGT/bolt#34]
When you click the logout button, you get the following error
```js
TypeError: "listener" argument must be a function
    at ClientRequest.once (events.js:340:11)
    at new ClientRequest (_http_client.js:164:10)
    at Object.request (http.js:38:10)
    at Object.request (https.js:239:15)
    at exports.authRoutes.all (C:\Users\Evan\Documents\GitHub\bolt\server\build\auth\auth.js:97:19)
    at Layer.handle [as handle_request] (C:\Users\Evan\Documents\GitHub\bolt\server\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Evan\Documents\GitHub\bolt\server\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\Evan\Documents\GitHub\bolt\server\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\Evan\Documents\GitHub\bolt\server\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Evan\Documents\GitHub\bolt\server\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\Evan\Documents\GitHub\bolt\server\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\Evan\Documents\GitHub\bolt\server\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\Evan\Documents\GitHub\bolt\server\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\Evan\Documents\GitHub\bolt\server\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\Evan\Documents\GitHub\bolt\server\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\Evan\Documents\GitHub\bolt\server\node_modules\express\lib\router\index.js:317:13)```

**Comment by evan10s** [comment]
Logout is no longer broken on https://bolt.dev.hack.gt, closing
